

-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20000, 'fr', 'RABAT');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20000, 'ar', 'الرباط');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES(20001, 'fr', 'CASABLANCA');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20001, 'ar', 'الدار البيضاء');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES(20002, 'fr', 'Laâyoune');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20002, 'ar', 'العيون');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20003, 'fr', 'Agadir');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20003, 'ar', 'أكادير');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20004, 'fr', 'Ouarzazate');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20004, 'ar', 'ورزازات');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20005, 'fr', 'Kénitra');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20005, 'ar', 'القنيطرة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20006, 'fr', 'Settat');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20006, 'ar', 'سطات');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20007, 'fr', 'Khouribga');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20007, 'ar', 'الخريبكة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20008, 'fr', 'Marrakech');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20008, 'ar', 'مراكش');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20009, 'fr', 'Safi');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20009, 'ar', 'آسفي');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20010, 'fr', 'Tanger');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20010, 'ar', 'طنجة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20011, 'fr', 'Tétouan');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20011, 'ar', 'تطوان');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20012, 'fr', 'AL Hoceima');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20012, 'ar', 'الحسيمة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20013, 'fr', 'Taza');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20013, 'ar', 'تازة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20014, 'fr', 'Oujda');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20014, 'ar', 'Oujda');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20015, 'fr', 'Meknès');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20015, 'ar', 'مكناس');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20016, 'fr', 'AL Jadida');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20016, 'ar', 'الجديدة');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20017, 'fr', 'Béni Mellal');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20017, 'ar', 'بني ملال');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20018, 'fr', 'Errachidia');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20018, 'ar', 'الراشدية');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20019, 'fr', 'Nador');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20019, 'ar', 'الناظور');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20020, 'fr', 'Fès');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20020, 'ar', 'فاس');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20021, 'fr', 'Guelmim');
-- INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20021, 'ar', 'كلميم');


INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20022', 'fr', 'Cour d\'appel de Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20022', 'ar', 'محكمة الاستئناف بالرباط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20023', 'fr', 'Cour d\'appel administrative de Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20023', 'ar', 'محكمة الاستئناف الإدارية بالرابط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20024', 'fr', 'Cour d\'appel de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20024', 'ar', 'محكمة الاستئناف بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20025', 'fr', 'Cour d\'appel de commerce de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20025', 'ar', 'محكمة الاستئناف التجارية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20026', 'fr', 'Cour d\'appel de Laâyoune');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20026', 'ar', 'محكمة الاستئناف بالعيون');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20027', 'fr', 'Cour d\'appel  d\'Ouarzazate');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20027', 'ar', 'محكمة الاستئناف بورزازات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20028', 'fr', 'Cour d\'appel  d\'Agadir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20028', 'ar', 'محكمة الاستئناف بأكادير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20029', 'fr', 'Cour d\'appel de Kénitra');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20029', 'ar', 'محكمة الاستئناف بالقنيطرة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20030', 'fr', 'Cour d\'appel de Settat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20030', 'ar', 'محكمة الاستئناف بسطات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20031', 'fr', 'Cour d\'appel de Khouribga');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20031', 'ar', 'محكمة الاستئناف بالخريبكة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20032', 'fr', 'Cour d\'appel de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20032', 'ar', 'محكمة الاستئناف بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20033', 'fr', 'Cour d\'appel de commerce de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20033', 'ar', 'محكمة الاستئناف التجارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20034', 'fr', 'Cour d\'appel administrative de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20034', 'ar', 'محكمة الاستئناف االإدارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20035', 'fr', 'Cour d\'appel de Safi');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20035', 'ar', 'محكمة الاستئناف بآسفي');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20036', 'fr', 'Cour d\'appel de Tanger');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20036', 'ar', 'محكمة الاستئناف بطنجة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20037', 'fr', 'Cour d\'appel de Tétouan');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20037', 'ar', 'محكمة الاستئناف بتطوان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20038', 'fr', 'Cour d\'appel  d\'AL Hoceima');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20038', 'ar', 'محكمة الاستئناف بالحسيمة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20039', 'fr', 'Cour d\'appel de Taza');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20039', 'ar', 'محكمة الاستئناف بتازة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20040', 'fr', 'Cour d\'appel d\'Oujda');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20040', 'ar', 'محكمة الاستئناف بوجدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20041', 'fr', 'Cour d\'appel  de Meknès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20041', 'ar', 'محكمة الاستئناف بمكناس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20042', 'fr', 'Cour d\'appel  d\'AL Jadida');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20042', 'ar', 'محكمة الاستئناف بالجديدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20043', 'fr', 'Cour d\'appel de Béni Mellal');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20043', 'ar', 'محكمة الاستئناف ببني ملال');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20044', 'fr', 'Cour d\'appel d\'Errachidia');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20044', 'ar', 'محكمة الاستئناف بالراشدية');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20045', 'fr', 'Cour d\'appel de Nador');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20045', 'ar', 'محكمة الاستئناف بالناظور');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20046', 'fr', 'Cour d\'appel de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20046', 'ar', 'محكمة الاستئناف بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20047', 'fr', 'Cour d\'appel de commerce de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20047', 'ar', 'محكمة الاستئناف التجارية بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20048', 'fr', 'Cour d\'appel de Guelmim');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20048', 'ar', 'محكمة الاستئناف بكلميم');


INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20049', 'fr', 'Cour d\'appel Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20049', 'ar', 'محكمة الاستئناف بالرباط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20050', 'fr', 'Tribunal de première instance de Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20050', 'ar', 'المحكمة الابتدائية  بالرباط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20051', 'fr', 'Tribunal de première instance de Salé');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20051', 'ar', 'المحكمة الابتدائية بسلا');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20052', 'fr', 'Tribunal de première instance de Témara');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20052', 'ar', 'المحكمة الابتدائية  بتمارة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20053', 'fr', 'Tribunal de première instance de Khemissat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20053', 'ar', 'المحكمة الابتداية  بالخميسات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20054', 'fr', 'Tribunal de première instance de Romani');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20054', 'ar', ' المحكمة الابتداية بالرماني');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20055', 'fr', 'Tribunal de première instance de Tifelt');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20055', 'ar', ' المحكمة الابتدائية  بتيفلت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20056', 'fr', 'Cour d\'appel administrative de  Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20056', 'ar', 'محكمة الاستئناف الادارية بالرباط  ');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20057', 'fr', 'Tribunal Administrative de Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20057', 'ar', 'المحكمة الادارية بالرباط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20058', 'fr', 'Tribunal Administrative de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20058', 'ar', 'المحكمة الادارية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20059', 'fr', 'Tribunal Administrative de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20059', 'ar', 'المحكمة الادارية بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20060', 'fr', 'Tribunal Administrative de Meknès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20060', 'ar', 'المحكمة الادارية بمكناس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20061', 'fr', 'Tribunal Administrative d\'Oujda');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20061', 'ar', ' المحكمة الادارية بوجدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20062', 'fr', 'Cour d\'appel de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20062', 'ar', 'محكمة الاستئناف بالدر البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20063', 'fr', 'Tribunal de première instance de Benslimane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20063', 'ar', ' المحكمة الابتدائية ببنسليمان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20064', 'fr', 'Tribunal de première instance civil de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20064', 'ar', ' المحكمة الابتدائية المدنية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20065', 'fr', 'Tribunal de première instance de Mohammedia');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20065', 'ar', ' المحكمة الابتدائية بالمحمدية');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20066', 'fr', 'Tribunal de première instance pénal de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20066', 'ar', ' المحكمة الابتدائية الزجرية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20067', 'fr', 'Tribunal de première instance social de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20067', 'ar', ' المحكمة الابتدائية الاجتماعية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20068', 'fr', 'Cour d\'appel de Commerce de Casablanca');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20068', 'ar', 'محكمة الاستئناف التجارية بالدار البيضاء');
-- INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20069', 'fr', 'Tribunal de commerce de Casablanca');
-- INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20069', 'ar', 'المحكمة التجارية بالدار البيضاء');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20070', 'fr', 'Tribunal de commerce de Rabat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20070', 'ar', 'المحكمة التجارية بالرباط');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20071', 'fr', 'Cour d\'appel de  Laâyoune');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20071', 'ar', 'محكمة الاستئناف بالعيون  ');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20072', 'fr', 'Tribunal de première instance de Dakhla');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20072', 'ar', 'المحكمة الابتدائية بالداخلة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20073', 'fr', 'Tribunal de première instance de Laâyoune');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20073', 'ar', 'المحكمة الابتدائية بالعيون ');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20074', 'fr', 'Tribunal de première instance de Semara');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20074', 'ar', 'المحكمة الابتدائية بالسمارة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20075', 'fr', 'Cour d\'appel d\'Ouarzazate');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20075', 'ar', 'محكمة الاستئناف بورزازات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20076', 'fr', 'Tribunal de première instance de Ouarzazate');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20076', 'ar', 'المحكمة الابتدائية بورزازات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20077', 'fr', 'Tribunal de première instance de Zagoura');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20077', 'ar', 'المحكمة الابتدائية بزاكورة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20078', 'fr', 'Tribunal de première instance de Tinghir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20078', 'ar', 'المحكمة الابتدائية بتنغير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20079', 'fr', 'Cour d\'appel d\'Agadir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20079', 'ar', 'محكمة الاستئناف بأكادير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20080', 'fr', 'Tribunal de première instance de Tata');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20080', 'ar', ' المحكمة الابتدائية بطاطا');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20081', 'fr', 'Tribunal de première instance de Inzegane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20081', 'ar', 'المحكمة الابتدائية بإنزكان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20082', 'fr', 'Tribunal de première instance de Taroudant');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20082', 'ar', ' المحكمة الابتدائية بتارودانت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20083', 'fr', 'Tribunal de première instance de Tiznit ');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20083', 'ar', 'المحكمة الابتدائية بتيزنيت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20084', 'fr', 'Tribunal de première instance d\'Agadir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20084', 'ar', ' المحكمة الابتدائية بأكادير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20085', 'fr', 'Cour d\'appel de Kénitra');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20085', 'ar', 'محكمة الاستئناف بالقنيطرة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20086', 'fr', 'Tribunal de première instance de Kénitra');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20086', 'ar', 'المحكمة الابتدائية بالقنيطرة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20087', 'fr', 'Tribunal de première instance de Sidi Slimane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20087', 'ar', 'المحكمة الابتدائية بسيدي سليمان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20088', 'fr', 'Tribunal de première instance de Souk Larbaa');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20088', 'ar', ' المحكمة الابتدائية بسوق أربعاء الغرب');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20089', 'fr', 'Tribunal de première instance de Sidi Kacem');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20089', 'ar', ' المحكمة الابتدائية بسيدي قاسم');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20090', 'fr', 'Tribunal de première instance de Belaksiri');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20090', 'ar', ' المحكمة الابتدائية بمشرع بلقصيري');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20091', 'fr', 'Cour d\'appel de Settat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20091', 'ar', 'محكمة الاستئناف بسطات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20092', 'fr', 'Tribunal de première instance de Settat');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20092', 'ar', ' المحكمة الابتدائية بسطات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20093', 'fr', 'Tribunal de première instance de Berrechid');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20093', 'ar', 'المحكمة الابتدائية ببرشيد');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20094', 'fr', 'Tribunal de première instance de Ben Ahmed');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20094', 'ar', 'المحكمة الابتدائية ببن أحمد');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20095', 'fr', 'Cour d\'appel de Khouribga');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20095', 'ar', 'محكمة الاستئناف بالخريبكة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20096', 'fr', 'Tribunal de première instance de Khouribga');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20096', 'ar', 'المحكمة الابتدائية بالخريبكة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20097', 'fr', 'Tribunal de première instance de Oued Zem');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20097', 'ar', 'المحكمة الابتدائية بوادي زم');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20098', 'fr', 'Tribunal de première instance de Bejaad');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20098', 'ar', 'المحكمة الابتدائية بأبي الجعد');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20099', 'fr', 'Cour d\'appel de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20099', 'ar', ' محكمة الاستئناف بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20100', 'fr', 'Tribunal de première instance d\'Imantanoute');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20100', 'ar', ' المحكمة الابتدائية بإيمنتانوت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20101', 'fr', 'Tribunal de première instance de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20101', 'ar', ' المحكمة الابتدائية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20102', 'fr', 'Tribunal de première instance de Kelaa de Sraghna');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20102', 'ar', ' المحكمة الابتدائية بقلعة السراغنة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20103', 'fr', 'Tribunal de première instance de benguerir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20103', 'ar', ' المحكمة الابتدائية بابن جرير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20104', 'fr', 'Cour d\'appel de Commerce de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20104', 'ar', ' محكمة الاستئناف التجارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20105', 'fr', 'Tribunal de commerce d\'Agadir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20105', 'ar', ' المحكمة التجارية بأكادير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20106', 'fr', 'Tribunal de commerce de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20106', 'ar', ' المحكمة التجارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20107', 'fr', 'Cour d\'appel Administrative de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20107', 'ar', ' محكمة الاستئناف الادارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20108', 'fr', 'Tribunal Administrative de Marrakech');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20108', 'ar', 'المحكمة الادارية بمراكش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20109', 'fr', 'Tribunal Administrative d\'Agadir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20109', 'ar', ' المحكمة الادارية بأكادير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20110', 'fr', 'Cour d\'appel de Safi');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20110', 'ar', 'محكمة الاستئناف بآسفي');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20111', 'fr', 'Tribunal de première instance de Essaouira');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20111', 'ar', 'المحكمة الابتدائية بالصويرة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20112', 'fr', 'Tribunal de première instance de Safi');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20112', 'ar', ' المحكمة الابتدائية بآسفي');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20113', 'fr', 'Tribunal de première instance d\'Al youssoufia');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20113', 'ar', ' المحكمة الابتدائية باليوسفية');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20114', 'fr', 'Cour d\'appel de Tanger');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20114', 'ar', ' محكمة الاستئناف بطنجة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20115', 'fr', 'Tribunal de première instance de Tanger');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20115', 'ar', 'المحكمة الابتدائية بطنجة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20116', 'fr', 'Tribunal de première instance d\'Assilah');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20116', 'ar', ' المحكمة الابتدائية بأصيلة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20117', 'fr', 'Tribunal de première instance de Larache');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20117', 'ar', ' المحكمة الابتدائية بالعرائش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20118', 'fr', 'Tribunal de première instance de Ksar El Kebir');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20118', 'ar', ' المحكمة الابتدائية بالقصر الكبير');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20119', 'fr', 'Cour d\'appel de Tétouan');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20119', 'ar', 'محكمة الاستئناف بتطوان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20120', 'fr', 'Tribunal de première instance de Ouazzane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20120', 'ar', ' المحكمة الابتدائية بوزان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20121', 'fr', 'Tribunal de première instance de Tétouan');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20121', 'ar', ' المحكمة الابتدائية بتطوان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20122', 'fr', 'Tribunal de première instance de Chefchaouen');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20122', 'ar', ' المحكمة الابتدائية بشفشاون');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20123', 'fr', 'Cour d\'appel d\'AL Hoceima');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20123', 'ar', ' محكمة الاستئناف بالحسيمة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20124', 'fr', 'Tribunal de première instance d\'AL Hoceima');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20124', 'ar', ' المحكمة الابتدائية بالحسيمة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20125', 'fr', 'Tribunal de première instance de Targuist');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20125', 'ar', ' المحكمة الابتدائية بتارجيست');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20126', 'fr', 'Cour d\'appel de Taza');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20126', 'ar', 'محكمة الاستئناف بتازة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20127', 'fr', 'Tribunal de première instance de Taza');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20127', 'ar', ' المحكمة الابتدائية بتازة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20128', 'fr', 'Cour d\'appel d\'Oujda');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20128', 'ar', ' محكمة الاستئناف بوجدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20129', 'fr', 'Tribunal de première instance d\'Oujda');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20129', 'ar', ' المحكمة الابتدائية بوجدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20130', 'fr', 'Tribunal de première instance de Berkane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20130', 'ar', ' المحكمة الابتدائية ببركان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20131', 'fr', 'Tribunal de première instance de Guercif');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20131', 'ar', ' المحكمة الابتدائية بجرسيف');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20132', 'fr', 'Tribunal de première instance de Taourirt');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20132', 'ar', ' المحكمة الابتدائية بتاوريرت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20133', 'fr', 'Tribunal de première instance de Feguig');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20133', 'ar', ' المحكمة الابتدائية بفجيج');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20134', 'fr', 'Cour d\'appel de Meknès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20134', 'ar', 'محكمة الاستئناف بمكناس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20135', 'fr', 'Tribunal de première instance de Meknès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20135', 'ar', ' المحكمة الابتدائية بمكناس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20136', 'fr', 'Tribunal de première instance d\'Azrou');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20136', 'ar', 'المحكمة الابتدائية بآزرو');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20137', 'fr', 'Cour d\'appel d\'AL Jadida');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20137', 'ar', ' محكمة الاستئناف بالجديدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20138', 'fr', 'Tribunal de première instance d\'AL Jadida');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20138', 'ar', 'المحكمة الابتدائية بالجديدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20139', 'fr', 'Tribunal de première instance de Sidi Benour');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20139', 'ar', ' المحكمة الابتدائية بسيدي بنور');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20140', 'fr', 'Cour d\'appel deBéni Mellal');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20140', 'ar', ' محكمة الاستئناف ببني ملال');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20141', 'fr', 'Tribunal de première instance de Béni Mellal');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20141', 'ar', ' المحكمة الابتدائية ببني ملال');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20142', 'fr', 'Tribunal de première instance d\'Azilal');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20142', 'ar', 'المحكمة الابتدائية بأزيلال');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20143', 'fr', 'Tribunal de première instance de Fquih Ben Saleh');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20143', 'ar', ' المحكمة الابتدائية بالفقيه بن صالح');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20144', 'fr', 'Tribunal de première instance de Khenifra');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20144', 'ar', '  المحكمة الابتدائية بخنيفرة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20145', 'fr', 'Tribunal de première instance de de Kasba Tadla');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20145', 'ar', ' المحكمة الابتدائية بقصبة تادلة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20146', 'fr', 'Tribunal de première instance de Souk Sebt ');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20146', 'ar', ' المحكمة الابتدائية بسوق السبت أولاد النمة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20147', 'fr', 'Cour d\'appel d\'Errachidia');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20147', 'ar', ' محكمة الاستئناف بالرشيدية');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20148', 'fr', 'Tribunal de première instance d\'Errachidia');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20148', 'ar', ' المحكمة الابتدائية بالرشيدية');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20149', 'fr', 'Tribunal de première instance de Midelt');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20149', 'ar', ' المحكمة الابتدائية بميدلت');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20150', 'fr', 'Cour d\'appel de Nador');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20150', 'ar', 'محكمة الاستئناف بالناظور');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20151', 'fr', 'Tribunal de première instance de Nador');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20151', 'ar', 'المحكمة الابتدائية بالناظور');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20152', 'fr', 'Tribunal de première instance de Driouch');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20152', 'ar', ' المحكمة الابتدائية بالدريوش');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20153', 'fr', 'Cour d\'appel de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20153', 'ar', 'محكمة الإستئناف بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20154', 'fr', 'Tribunal de première instance de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20154', 'ar', ' المحكمة الابتدائية بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20155', 'fr', 'Tribunal de première instance de Boulmane');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20155', 'ar', 'المحكمة الابتدائية ببولمان');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20156', 'fr', 'Tribunal de première instance de Sefrou');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20156', 'ar', 'المحكمة الابتدائية بصفرو');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20157', 'fr', 'Tribunal de première instance de Taounate');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20157', 'ar', 'المحكمة الابتدائية بتـــاونات');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20158', 'fr', 'Cour d\'appel de commerce Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20158', 'ar', 'محكمة الإستئناف التجارية بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20159', 'fr', 'Tribunal de commerce de Fès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20159', 'ar', 'المحكمة التجارية بفاس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20160', 'fr', 'Tribunal de commerce de Meknès');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20160', 'ar', 'المحكمة التجارية بمكناس');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20161', 'fr', 'Tribunal de commerce d\'Oujda');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20161', 'ar', 'المحكمة التجارية بوجدة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20162', 'fr', 'Tribunal de commerce de Tanger');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20162', 'ar', 'المحكمة التجارية بطنجة');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20163', 'fr', 'Cour d\'appel de Guelmim');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20163', 'ar', 'محكمة الإستئناف بكلميم');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20164', 'fr', 'Tribunal de première instance de Guelmim');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20164', 'ar', ' المحكمة الابتدائية بكلميم');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20165', 'fr', 'Tribunal de première instance de Tantan');
INSERT INTO `T_TRADUCTION_LIBELLE` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES ('20165', 'ar', ' المحكمة الابتدائية بطانطان');


INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20000, NULL, '20000', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20001, NULL, '20001', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20002, NULL, '20002', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20003, NULL, '20003', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20004, NULL, '20004', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20005, NULL, '20005', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20006, NULL, '20006', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20007, NULL, '20007', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20008, NULL, '20008', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20009, NULL, '20009', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20010, NULL, '20010', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20011, NULL, '20011', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20012, NULL, '20012', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20013, NULL, '20013', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20014, NULL, '20014', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20015, NULL, '20015', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20016, NULL, '20016', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20017, NULL, '20017', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20018, NULL, '20018', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20019, NULL, '20019', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20020, NULL, '20020', '1');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20021, NULL, '20021', '1');

INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20022, '20000', '20022', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20023, '20000','20023', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20024, '20001', '20024', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20025, '20001', '20025', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20026, '20002', '20026', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20027, '20003', '20027', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20028, '20004', '20028', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20029, '20005', '20029', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20030, '20006', '20030', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20031, '20007', '20031', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20032, '20008', '20032', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20033, '20008', '20033', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20034, '20008', '20034', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20035, '20009', '20035', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20036, '20010', '20036', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20037, '20011', '20037', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20038, '20012', '20038', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20039, '20013', '20039', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20040, '20014', '20040', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20041, '20015', '20041', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20042, '20016', '20042', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20043, '20017', '20043', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20044, '20018', '20044', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20045, '20019', '20045', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20046, '20020', '20046', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20047, '20020', '20047', '2');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20048, '20021', '20048', '2');


INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20049, '20022', '20049', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20050, '20022', '20050', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20051, '20022', '20051', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20052, '20022', '20052', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20053, '20022', '20053', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20054, '20022', '20054', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20055, '20022', '20055', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20056, '20023', '20056', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20057, '20023', '20057', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20058, '20023', '20058', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20059, '20023', '20059', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20060, '20023', '20060', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20061, '20023', '20061', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20062, '20024', '20062', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20063, '20024', '20063', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20064, '20024', '20064', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20065, '20024', '20065', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20066, '20024', '20066', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20067, '20024', '20067', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20068, '20025', '20068', '3');
-- INSERT INTO `t_entite` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20069, '20025', '20069', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20070, '20025', '20070', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20071, '20026', '20071', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20072, '20026', '20072', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20073, '20026', '20073', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20074, '20026', '20074', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20075, '20027', '20075', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20076, '20027', '20076', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20077, '20027', '20077', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20078, '20027', '20078', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20079, '20028', '20079', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20080, '20028', '20080', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20081, '20028', '20081', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20082, '20028', '20082', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20083, '20028', '20083', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20084, '20028', '20084', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20085, '20029', '20085', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20086, '20029', '20086', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20087, '20029', '20087', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20088, '20029', '20088', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20089, '20029', '20089', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20090, '20029', '20090', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20091, '20030', '20091', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20092, '20030', '20092', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20093, '20030', '20093', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20094, '20030', '20094', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20095, '20031', '20095', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20096, '20031', '20096', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20097, '20031', '20097', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20098, '20031', '20098', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20099, '20032', '20099', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20100, '20032', '20100', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20101, '20032', '20101', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20102, '20032', '20102', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20103, '20032', '20103', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20104, '20033', '20104', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20105, '20033', '20105', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20106, '20033', '20106', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20107, '20034', '20107', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20108, '20034', '20108', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20109, '20034', '20109', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20110, '20035', '20110', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20111, '20035', '20111', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20112, '20035', '20112', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20113, '20035', '20113', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20114, '20036', '20114', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20115, '20036', '20115', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20116, '20036', '20116', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20117, '20036', '20117', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20118, '20036', '20118', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20119, '20037', '20119', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20120, '20037', '20120', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20121, '20037', '20121', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20122, '20037', '20122', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20123, '20038', '20123', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20124, '20038', '20124', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20125, '20038', '20125', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20126, '20039', '20126', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20127, '20039', '20127', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20128, '20040', '20128', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20129, '20040', '20129', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20130, '20040', '20130', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20131, '20040', '20131', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20132, '20040', '20132', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20133, '20040', '20133', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20134, '20041', '20134', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20135, '20041', '20135', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20136, '20041', '20136', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20137, '20042', '20137', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20138, '20042', '20138', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20139, '20042', '20139', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20140, '20043', '20140', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20141, '20043', '20141', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20142, '20043', '20142', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20143, '20043', '20143', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20144, '20043', '20144', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20145, '20043', '20145', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20146, '20043', '20146', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20147, '20044', '20147', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20148, '20044', '20148', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20149, '20044', '20149', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20150, '20045', '20150', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20151, '20045', '20151', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20152, '20045', '20152', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20153, '20046', '20153', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20154, '20046', '20154', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20155, '20046', '20155', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20156, '20046', '20156', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20157, '20046', '20157', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20158, '20047', '20158', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20159, '20047', '20159', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20160, '20047', '20160', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20161, '20047', '20161', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20162, '20047', '20162', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20163, '20048', '20163', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20164, '20048', '20164', '3');
INSERT INTO `T_ENTITE` (`ID_ENTITE`, `ID_ENTITE_PARENT`, `CODE_LIBELLE`, `NIVEAU`) VALUES (20165, '20048', '20165', '3');

