INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20000, 'fr', 'RABAT');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20000, 'ar', 'الرباط');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20001, 'fr', 'CASABLANCA');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20001, 'ar', 'الدار البيضاء');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20002, 'fr', 'Laâyoune');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20002, 'ar', 'العيون');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20003, 'fr', 'Agadir');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20003, 'ar', 'أكادير');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20004, 'fr', 'Ouarzazate');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20004, 'ar', 'ورزازات');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20005, 'fr', 'Kénitra');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20005, 'ar', 'القنيطرة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20006, 'fr', 'Settat');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20006, 'ar', 'سطات');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20007, 'fr', 'Khouribga');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20007, 'ar', 'الخريبكة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20008, 'fr', 'Marrakech');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20008, 'ar', 'مراكش');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20009, 'fr', 'Safi');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20009, 'ar', 'آسفي');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20010, 'fr', 'Tanger');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20010, 'ar', 'طنجة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20011, 'fr', 'Tétouan');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20011, 'ar', 'تطوان');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20012, 'fr', 'AL Hoceima');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20012, 'ar', 'الحسيمة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20013, 'fr', 'Taza');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20013, 'ar', 'تازة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20014, 'fr', 'Oujda');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20014, 'ar', 'Oujda');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20015, 'fr', 'Meknès');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20015, 'ar', 'مكناس');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20016, 'fr', 'AL Jadida');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20016, 'ar', 'الجديدة');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20017, 'fr', 'Béni Mellal');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20017, 'ar', 'بني ملال');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20018, 'fr', 'Errachidia');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20018, 'ar', 'الراشدية');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20019, 'fr', 'Nador');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20019, 'ar', 'الناظور');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20020, 'fr', 'Fès');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20020, 'ar', 'فاس');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20021, 'fr', 'Guelmim');
INSERT INTO `t_traduction_libelle` (`ID_TRADUCTION`, `LANG`, `LIBELLE`) VALUES (20021, 'ar', 'كلميم');
